"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-30T12:57:53Z).

Frozen, fully expanded cobaya configuration for example2
(source: EXAMPLE_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.1,
    "H0": 67.32,
    "mnu": 0.06,
    "ns": 0.96605,
    "omegab": 0.04,
    "omegam": 0.3,
    "roman_A1_1": 0.6,
    "roman_A1_2": -1.5,
    "roman_A2_1": 0.0,
    "roman_A2_2": -1.51541,
    "roman_B1_1": 1.18,
    "roman_B1_2": 1.4,
    "roman_B1_3": 1.55,
    "roman_B1_4": 1.71,
    "roman_B1_5": 1.9,
    "roman_B1_6": 2.15,
    "roman_B1_7": 2.52,
    "roman_B1_8": 2.44,
    "roman_BTA_1": 0.0,
    "roman_DZ_S1": 0.0,
    "roman_DZ_S2": 0.0,
    "roman_DZ_S3": 0.0,
    "roman_DZ_S4": 0.0,
    "roman_DZ_S5": 0.0,
    "roman_DZ_S6": 0.0,
    "roman_DZ_S7": 0.0,
    "roman_DZ_S8": 0.0,
    "roman_M1": 0.0,
    "roman_M2": 0.0,
    "roman_M3": 0.0,
    "roman_M4": 0.0,
    "roman_M5": 0.0,
    "roman_M6": 0.0,
    "roman_M7": 0.0,
    "roman_M8": 0.0,
    "w": -1.0,
    "w0pwa": -1.0
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.2
    proposal: 0.2
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.015
    proposal: 0.015
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 3
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.005
    proposal: 0.005
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.015
    proposal: 0.015
    latex: \Omega_\mathrm{m}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
    derived: true
  mnu:
    prior:
      min: 0.06
      max: 0.6
    ref:
      dist: norm
      loc: 0.25
      scale: 0.1
    proposal: 0.05
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
    renames:
    - ombh2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
    renames:
    - omch2
  omegal:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omega_de
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  yheused:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YHe
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
    derived: true
    renames:
    - omnuh2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  roman_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^1
  roman_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^2
  roman_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^3
  roman_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^4
  roman_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^5
  roman_DZ_S6:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^6
  roman_DZ_S7:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^7
  roman_DZ_S8:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,roman}^8
  roman_M1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^1
  roman_M2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^2
  roman_M3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^3
  roman_M4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^4
  roman_M5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^5
  roman_M6:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^6
  roman_M7:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^7
  roman_M8:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{roman}^8
  roman_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,roman}^1
  roman_A1_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,roman}^2
  roman_A2_1:
    latex: A_\mathrm{2-IA,Roman}^1
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.36
      scale: 0.5
    proposal: 0.5
  roman_A2_2:
    latex: A_\mathrm{2-IA,Roman}^2
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -2.5
      scale: 0.5
    proposal: 0.5
  roman_BTA_1:
    latex: A_\mathrm{BTA-IA,Roman}^1
    prior:
      min: 0
      max: 2
    ref:
      dist: norm
      loc: 1
      scale: 0.15
    proposal: 0.1
  roman_DZ_L1:
    value: 'lambda roman_DZ_S1: roman_DZ_S1'
    latex: \Delta z_\mathrm{l,Roman}^1
    derived: true
  roman_DZ_L2:
    value: 'lambda roman_DZ_S2: roman_DZ_S2'
    latex: \Delta z_\mathrm{l,Roman}^2
    derived: true
  roman_DZ_L3:
    value: 'lambda roman_DZ_S3: roman_DZ_S3'
    latex: \Delta z_\mathrm{l,Roman}^3
    derived: true
  roman_DZ_L4:
    value: 'lambda roman_DZ_S4: roman_DZ_S4'
    latex: \Delta z_\mathrm{l,Roman}^4
    derived: true
  roman_DZ_L5:
    value: 'lambda roman_DZ_S5: roman_DZ_S5'
    latex: \Delta z_\mathrm{l,Roman}^5
    derived: true
  roman_DZ_L6:
    value: 'lambda roman_DZ_S6: roman_DZ_S6'
    latex: \Delta z_\mathrm{l,Roman}^6
    derived: true
  roman_DZ_L7:
    value: 'lambda roman_DZ_S7: roman_DZ_S7'
    latex: \Delta z_\mathrm{l,Roman}^7
    derived: true
  roman_DZ_L8:
    value: 'lambda roman_DZ_S8: roman_DZ_S8'
    latex: \Delta z_\mathrm{l,Roman}^8
    derived: true
  roman_B1_1:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.24
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^1
  roman_B1_2:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.36
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^2
  roman_B1_3:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.47
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^3
  roman_B1_4:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.6
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^4
  roman_B1_5:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^5
  roman_B1_6:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.47
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^6
  roman_B1_7:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.6
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^7
  roman_B1_8:
    prior:
      min: 0.4
      max: 4
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-Roman}^8
  roman_PM1:
    value: 0.0
    latex: PM_\mathrm{Roman}^1
  roman_PM2:
    value: 0.0
    latex: PM_\mathrm{Roman}^2
  roman_PM3:
    value: 0.0
    latex: PM_\mathrm{Roman}^3
  roman_PM4:
    value: 0.0
    latex: PM_\mathrm{Roman}^4
  roman_PM5:
    value: 0.0
    latex: PM_\mathrm{Roman}^5
  roman_PM6:
    value: 0.0
    latex: PM_\mathrm{Roman}^6
  roman_PM7:
    value: 0.0
    latex: PM_\mathrm{Roman}^7
  roman_PM8:
    value: 0.0
    latex: PM_\mathrm{Roman}^8
  roman_BMAG_1:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^1
  roman_BMAG_2:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^2
  roman_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,roman}^3
  roman_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,roman}^4
  roman_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,roman}^5
  roman_A1_6:
    value: 0
    latex: A_\mathrm{1-IA,roman}^6
  roman_A1_7:
    value: 0
    latex: A_\mathrm{1-IA,roman}^7
  roman_A1_8:
    value: 0
    latex: A_\mathrm{1-IA,roman}^8
  roman_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^3
  roman_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^4
  roman_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^5
  roman_A2_6:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^6
  roman_A2_7:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^7
  roman_A2_8:
    value: 0
    latex: A_\mathrm{2-IA,Roman}^8
  roman_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^2
  roman_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^3
  roman_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^4
  roman_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^5
  roman_BTA_6:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^6
  roman_BTA_7:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^7
  roman_BTA_8:
    value: 0
    latex: A_\mathrm{BTA-IA,Roman}^8
  roman_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{roman}^1
  roman_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{roman}^2
  roman_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{roman}^3
  roman_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{roman}^4
  roman_B2_1:
    value: 0.0
    latex: b_\mathrm{2-Roman}^1
  roman_B2_2:
    value: 0.0
    latex: b_\mathrm{2-Roman}^2
  roman_B2_3:
    value: 0.0
    latex: b_\mathrm{2-Roman}^3
  roman_B2_4:
    value: 0.0
    latex: b_\mathrm{2-Roman}^4
  roman_B2_5:
    value: 0.0
    latex: b_\mathrm{2-Roman}^5
  roman_B2_6:
    value: 0.0
    latex: b_\mathrm{2-Roman}^6
  roman_B2_7:
    value: 0.0
    latex: b_\mathrm{2-Roman}^7
  roman_B2_8:
    value: 0.0
    latex: b_\mathrm{2-Roman}^8
  roman_BMAG_3:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^3
  roman_BMAG_4:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^4
  roman_BMAG_5:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^5
  roman_BMAG_6:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^6
  roman_BMAG_7:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^7
  roman_BMAG_8:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^8
  roman_B3NL_1:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^1
  roman_B3NL_2:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^2
  roman_B3NL_3:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^3
  roman_B3NL_4:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^4
  roman_B3NL_5:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^5
  roman_B3NL_6:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^6
  roman_B3NL_7:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^7
  roman_B3NL_8:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^8
  roman_BK_1:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^1
  roman_BK_2:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^2
  roman_BK_3:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^3
  roman_BK_4:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^4
  roman_BK_5:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^5
  roman_BK_6:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^6
  roman_BK_7:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^7
  roman_BK_8:
    value: 0.0
    latex: b_\mathrm{BMAG-Roman}^8
likelihood:
  roman_real.combo_3x2pt:
    path: ./projects/roman_real/tests/frozen/data
    data_file: example1.dataset
    accuracyboost: 1.0
    internal_accuracyboost: 1.0
    integration_accuracy: 0
    photoz_interpolation_type: 0
    photoz_zmid_convention: 0
    adopt_limber_gs: 0
    adopt_limber_gg: 0
    include_HOD_GX: 0
    include_halo_IA: 0
    lmax: 100000
    kmax_boltzmann: 7.5
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: false
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    ggl_exclude:
    - - 6
      - 0
    - - 7
      - 0
    - - 7
      - 1
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    external_baryon_suppression: false
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/roman_real/chains/pca.txt
    print_datavector: false
    print_datavector_file: ./projects/roman_real/chains/theory.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - As
    - roman_DZ_S1
    - roman_DZ_S2
    - roman_DZ_S3
    - roman_DZ_S4
    - roman_DZ_S5
    - roman_DZ_S6
    - roman_DZ_S7
    - roman_DZ_S8
    - roman_M1
    - roman_M2
    - roman_M3
    - roman_M4
    - roman_M5
    - roman_M6
    - roman_M7
    - roman_M8
    - roman_A1_1
    - roman_A1_2
    - roman_A2_1
    - roman_A2_2
    - roman_BTA_1
    - roman_DZ_L1
    - roman_DZ_L2
    - roman_DZ_L3
    - roman_DZ_L4
    - roman_DZ_L5
    - roman_DZ_L6
    - roman_DZ_L7
    - roman_DZ_L8
    - roman_B1_1
    - roman_B1_2
    - roman_B1_3
    - roman_B1_4
    - roman_B1_5
    - roman_B1_6
    - roman_B1_7
    - roman_B1_8
    - roman_PM1
    - roman_PM2
    - roman_PM3
    - roman_PM4
    - roman_PM5
    - roman_PM6
    - roman_PM7
    - roman_PM8
    - roman_BMAG_1
    - roman_BMAG_2
    - roman_A1_3
    - roman_A1_4
    - roman_A1_5
    - roman_A1_6
    - roman_A1_7
    - roman_A1_8
    - roman_A2_3
    - roman_A2_4
    - roman_A2_5
    - roman_A2_6
    - roman_A2_7
    - roman_A2_8
    - roman_BTA_2
    - roman_BTA_3
    - roman_BTA_4
    - roman_BTA_5
    - roman_BTA_6
    - roman_BTA_7
    - roman_BTA_8
    - roman_BARYON_Q1
    - roman_BARYON_Q2
    - roman_BARYON_Q3
    - roman_BARYON_Q4
    - roman_B2_1
    - roman_B2_2
    - roman_B2_3
    - roman_B2_4
    - roman_B2_5
    - roman_B2_6
    - roman_B2_7
    - roman_B2_8
    - roman_BMAG_3
    - roman_BMAG_4
    - roman_BMAG_5
    - roman_BMAG_6
    - roman_BMAG_7
    - roman_BMAG_8
    - roman_B3NL_1
    - roman_B3NL_2
    - roman_B3NL_3
    - roman_B3NL_4
    - roman_B3NL_5
    - roman_B3NL_6
    - roman_B3NL_7
    - roman_B3NL_8
    - roman_BK_1
    - roman_BK_2
    - roman_BK_3
    - roman_BK_4
    - roman_BK_5
    - roman_BK_6
    - roman_BK_7
    - roman_BK_8
    output_params: []
theory:
  camb:
    version: 1.6.7
    path: ./external_modules/code/CAMB
    speed: 0.3
    stop_at_error: false
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.1
      lens_potential_accuracy: 1.0
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 15
      kmax: 10.0
    ignore_obsolete: false
    use_renames: true
    external_primordial_pk: false
    use_non_linear_ratio: false
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      omegan2: omnuh2
    input_params:
    - ns
    - As
    - H0
    - w
    - wa
    - mnu
    - tau
    - omegabh2
    - omegach2
    output_params:
    - omegal
    - sigma8
    - age
    - rdrag
    - yheused
    - omegan2
timing: false
"""
