"""Maintainer tool: (re)create the frozen state the unit tests run on.

Running this REDEFINES what the tests protect, so it refuses to run
without the explicit --overwrite flag. Only run it when a change to
the data vectors, n(z), covariance, examples, or likelihood defaults
is deliberate, and review the printed chi2 values before committing:
they become the new references the tests compare against.

What one run produces, all under tests/ (see cocoa_test_utils for how
the tests consume each piece):

  - frozen/data/: a copy of the CURRENT ../data folder.
  - frozen/EXAMPLE_EVALUATE{1,2}.yaml: snapshots of the current
    examples, kept for humans to diff (the tests never load them).
  - frozen/frozen_config_example{1,2}.py: for each example, the model
    is built from the CURRENT example yaml, cobaya resolves it against
    the CURRENT likelihood defaults, and the complete resolved
    configuration is written back out as a yaml string, together with
    the exact evaluation point. Writing out every resolved option and
    parameter is what makes the tests independent of later edits to
    the live files.
  - frozen/reference_chi2.json: the four reference chi2 values
    (example1/2, each with NLA and TATT), computed FROM the frozen
    modules just written, exactly the way the tests will compute them.
  - frozen/halo_reference.json: the halo.c ground truth of
    test_halo.py - per-point values of every halo-model probe on the
    grids test_halo.py defines, at the configuration and HOD/gas
    parameters it pins (test_halo.build_halo_state).
  - manifest_sha256.json: the SHA-256 pin of every frozen file.

Usage (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python ./projects/roman_real/tests/generate_frozen_reference.py --overwrite

To rewrite only frozen/halo_reference.json in an existing frozen state
(and re-pin the manifest):

    python ./projects/roman_real/tests/generate_frozen_reference.py --halo
"""

import json
import os
import shutil
import sys
import time

# The references must be produced under the same OpenMP thread count
# the tests enforce, and before any cobaya/cosmolike import.
os.environ["OMP_NUM_THREADS"] = "4"

# __file__ is this script's own path; insert(0, ...) puts the tests/
# folder FIRST on the module search path, so the import below finds
# the harness no matter where the script was launched from
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

PROJECT_DIR = os.path.dirname(u.TESTS_DIR)

# Stored inside the frozen configurations as the likelihood data path.
# ROOTDIR-relative on purpose: the frozen modules stay portable across
# machines, and the tests overwrite it with the absolute path anyway.
FROZEN_DATA_RELPATH = "./projects/roman_real/tests/frozen/data"

# The skeleton of one generated frozen-configuration module. The yaml
# goes inside r""" so latex backslashes in parameter labels survive.
# The backslash right after the opening quotes below swallows the
# first newline, and the {name} slots are filled by .format later.
MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by generate_frozen_reference.py --overwrite ({stamp}).

Frozen, fully expanded cobaya configuration for {example}
(source: {source} resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {point}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
{yaml}
"""
'''


def freeze_example(example, stamp):
    """Write one example's fully expanded frozen-configuration module.

    The expansion works by round trip through cobaya: build the model
    from the live example yaml (letting cobaya merge in the live
    likelihood defaults), then ask the model for its resolved
    configuration with model.info() and store THAT. The resolved form
    lists every option and every parameter explicitly, so the frozen
    module no longer depends on any live default.

    Arguments:
      example = "example1" or "example2" (a key of u.EXAMPLES).
      stamp   = the UTC time string written into the module header.

    Returns:
      nothing; frozen/frozen_config_<example>.py is written.

    Raises:
      ValueError when a sampled parameter is neither overridden by the
      example's evaluate block nor given a ref center to fall back on
      (the point would be undefined at that parameter).
    """
    from cobaya.yaml import yaml_load_file, yaml_dump

    cfg = u.EXAMPLES[example]
    live = yaml_load_file(os.path.join(PROJECT_DIR, cfg["provenance"]))
    # The evaluate sampler's override block is the example's fiducial
    # point; keep it before stripping the sampler from the info.
    # dict(...) makes an independent COPY, so the pop below cannot
    # take the block with it.
    override = dict(live["sampler"]["evaluate"]["override"])
    live.pop("sampler", None)
    live.pop("output", None)
    live["debug"] = 30
    live["timing"] = False
    # the 2x2pt configuration reuses example2's yaml with the
    # likelihood renamed (combo_3x2pt -> combo_2x2pt: same options,
    # same data, different probe selection inside cosmolike)
    # .get falls back to the plain likelihood name for the entries
    # that carry no source_likelihood key
    source_name = cfg.get("source_likelihood", cfg["likelihood"])
    # pop removes the block from the dictionary AND hands it back, so
    # the next line can re-insert it under the target name
    likelihood_block = live["likelihood"].pop(source_name)
    live["likelihood"][cfg["likelihood"]] = likelihood_block
    likelihood_block["path"] = FROZEN_DATA_RELPATH
    likelihood_block["IA_model"] = 0

    # make_model builds the evaluable cobaya Model; building it is
    # what forces cobaya to merge the live likelihood defaults into
    # the configuration
    model = u.make_model(live)
    # model.info() returns the configuration with every default
    # resolved: the complete likelihood option set and the complete
    # parameter list, exactly what must be frozen.
    updated = model.info()
    updated.pop("output", None)
    updated.pop("packages_path", None)
    updated["likelihood"][cfg["likelihood"]]["path"] = FROZEN_DATA_RELPATH

    # The frozen point: the example's override where given, the ref
    # center otherwise. Fallbacks are printed so the maintainer can
    # confirm each one is intended.
    point = {}
    fallback = []
    for name in model.parameterization.sampled_params():
        if name in override:
            point[name] = override[name]
        else:
            # ref is either a {dist, loc, scale} block or a bare
            # number; the a-if-else picks the center in the first
            # case and the number itself in the second
            ref = updated["params"][name].get("ref")
            point[name] = ref["loc"] if isinstance(ref, dict) else ref
            fallback.append(name)
            if point[name] is None:
                raise ValueError(
                    f"parameter {name}: not in override and no ref")
    if fallback:
        print(f"{example}: point uses ref centers for {fallback}", flush=True)

    # the with block closes the file once the write finishes, even
    # on error. .format fills the template's {name} slots; json.dumps
    # renders the point as literal text (json syntax is valid python
    # here), sort_keys fixing the order; rstrip("\n") trims trailing
    # newlines so the template's closing quotes sit flush
    with open(os.path.join(u.FROZEN_DIR, cfg["frozen_module"]), "w") as f:
        f.write(MODULE_TEMPLATE.format(
            stamp=stamp,
            example=example,
            source=cfg["provenance"],
            point=json.dumps(point, indent=4, sort_keys=True),
            yaml=yaml_dump(updated).rstrip("\n"),
        ))
    print(f"{example}: frozen config expanded to "
          f"{len(updated['params'])} parameters "
          f"({len(live['params'])} in the live example yaml)", flush=True)


def generate_tatt_datavector(dataset_name):
    """Write one TATT-generated data vector and its dataset descriptor.

    The vector comes from the generating example named in
    u.TATT_GENERATORS, evaluated at the TATT point with datavector
    printing enabled. It must be generated against the ORIGINAL frozen
    dataset (the TATT descriptor written here does not exist yet; the
    printed theory vector does not depend on which data vector it is
    compared against). Runs inside a --tatt-one worker subprocess: it
    builds a model, and two different-dimension builds in one process
    abort (see cocoa_test_utils).

    Arguments:
      dataset_name = a key of u.TATT_GENERATORS, which is also the
                     file name of the descriptor to write.

    Returns:
      nothing; frozen/data/ gains the .modelvector and .dataset files.

    Raises:
      RuntimeError when the generated vector's length differs from
      the original data vector (a masking or probe mismatch), or when
      the dataset descriptor does not contain exactly one data_file
      line to replace.
    """
    from cobaya.yaml import yaml_load

    example = u.TATT_GENERATORS[dataset_name]
    cfg = u.EXAMPLES[example]
    # the original dataset name comes from the frozen configuration
    # itself (load_frozen_info would already point at the TATT dataset)
    frozen_info = yaml_load(u._frozen_module(example).yaml_string)
    original_dataset = frozen_info["likelihood"][cfg["likelihood"]]["data_file"]

    vector_name = dataset_name.replace(".dataset", ".modelvector")
    info = u.load_frozen_info(example, tatt=True)
    likelihood_block = info["likelihood"][cfg["likelihood"]]
    likelihood_block["data_file"] = original_dataset
    likelihood_block["print_datavector"] = True
    likelihood_block["print_datavector_file"] = (
        FROZEN_DATA_RELPATH + "/" + vector_name)

    print(f"generating {vector_name} ({example}, TATT point) ...",
          flush=True)
    model = u.make_model(info)
    point = u.build_point(model, example, tatt=True)
    u.evaluate_chi2(model, point)

    # sanity: the generated vector must have the same length as the
    # original one, or the masks would select the wrong entries
    data_dir = os.path.join(u.FROZEN_DIR, "data")
    with open(os.path.join(data_dir, vector_name)) as f:
        # sum(1 for _ in f) walks the file line by line and adds 1
        # per line: a line count that never loads the whole file into
        # memory (_ is the customary name for an unused value)
        generated_lines = sum(1 for _ in f)
    descriptor_path = os.path.join(data_dir, original_dataset)
    with open(descriptor_path) as f:
        descriptor = f.read()
    original_vector = None
    # splitlines() cuts the text into a list of lines, newlines
    # removed; strip() trims surrounding whitespace before the match
    for line in descriptor.splitlines():
        if line.strip().startswith("data_file"):
            # split("=", 1) cuts at the FIRST "=" only; [1] is the
            # part after it, stripped of spaces: the file name
            original_vector = line.split("=", 1)[1].strip()
    with open(os.path.join(data_dir, original_vector)) as f:
        # the same streaming line count as above
        original_lines = sum(1 for _ in f)
    if generated_lines != original_lines:
        raise RuntimeError(
            f"TATT data vector has {generated_lines} lines; the "
            f"original {original_vector} has {original_lines}")

    # the TATT dataset descriptor: the original with only the
    # data_file line replaced
    replaced = 0
    out_lines = []
    # keepends=True keeps each line's newline character, so the
    # rewritten descriptor reproduces the original line endings
    for line in descriptor.splitlines(keepends=True):
        if line.strip().startswith("data_file"):
            out_lines.append(f"data_file = {vector_name}\n")
            replaced += 1
        else:
            out_lines.append(line)
    if replaced != 1:
        raise RuntimeError(
            f"{original_dataset}: expected exactly one data_file "
            f"line, found {replaced}")
    with open(os.path.join(data_dir, dataset_name), "w") as f:
        # "".join glues the kept lines back into one text; nothing
        # is inserted between them (each line kept its newline)
        f.write("".join(out_lines))
    print(f"TATT data vector: {vector_name} ({generated_lines} lines); "
          f"descriptor: {dataset_name}", flush=True)


def generate_baryon_datavector(label):
    """Write one feedback method's frozen data vector and descriptor.

    The vector is the example1 theory prediction WITH the bfmt theory
    block computing this method's suppression, at the frozen fiducial
    point plus the method's cosmology override
    (u.BARYON_POINT_OVERRIDES, e.g. BACCOemu's omegab shift into its
    training box). The DRIFT tests of test_baryons.py evaluate
    against this vector: at freeze time the chi2 is zero by
    construction, so any later chi2 above the tolerance means
    cosmolike or the theory block changed its prediction. (The
    ACCURACY checks of test_accuracy_baryons.py do not use these
    files: they regenerate their vector on the fly per run.) Runs
    inside a --baryon-one worker subprocess for the same isolation
    reasons as the other steps.

    Arguments:
      label = a u.BARYON_METHODS label.

    Returns:
      nothing; frozen/data/ gains the .modelvector and .dataset files.

    Raises:
      RuntimeError when the generated vector's length differs from
      the original data vector, or when the dataset descriptor does
      not contain exactly one data_file line.
    """
    from cobaya.yaml import yaml_load

    example = "example1"
    cfg = u.EXAMPLES[example]
    frozen_info = yaml_load(u._frozen_module(example).yaml_string)
    original_dataset = frozen_info["likelihood"][cfg["likelihood"]]["data_file"]

    dataset_name = u._baryon_dataset(label)
    vector_name = dataset_name.replace(".dataset", ".modelvector")
    info = u.load_frozen_info(example, tatt=False, baryon=label)
    likelihood_block = info["likelihood"][cfg["likelihood"]]
    likelihood_block["data_file"] = original_dataset
    likelihood_block["print_datavector"] = True
    likelihood_block["print_datavector_file"] = (
        FROZEN_DATA_RELPATH + "/" + vector_name)

    print(f"generating {vector_name} ({label}) ...", flush=True)
    model = u.make_model(info)
    point = dict(u.build_point(model, example, tatt=False))
    point.update(u.BARYON_POINT_OVERRIDES.get(label, {}))
    u.evaluate_chi2(model, point)

    data_dir = os.path.join(u.FROZEN_DIR, "data")
    with open(os.path.join(data_dir, vector_name)) as f:
        generated_lines = sum(1 for _ in f)
    descriptor_path = os.path.join(data_dir, original_dataset)
    with open(descriptor_path) as f:
        descriptor = f.read()
    original_vector = None
    for line in descriptor.splitlines():
        if line.strip().startswith("data_file"):
            original_vector = line.split("=", 1)[1].strip()
    with open(os.path.join(data_dir, original_vector)) as f:
        original_lines = sum(1 for _ in f)
    if generated_lines != original_lines:
        raise RuntimeError(
            f"baryon data vector has {generated_lines} lines; the "
            f"original {original_vector} has {original_lines}")

    replaced = 0
    out_lines = []
    for line in descriptor.splitlines(keepends=True):
        if line.strip().startswith("data_file"):
            out_lines.append(f"data_file = {vector_name}\n")
            replaced += 1
        else:
            out_lines.append(line)
    if replaced != 1:
        raise RuntimeError(
            f"{original_dataset}: expected exactly one data_file "
            f"line, found {replaced}")
    with open(os.path.join(data_dir, dataset_name), "w") as f:
        f.write("".join(out_lines))
    print(f"baryon data vector: {vector_name} ({generated_lines} "
          f"lines); descriptor: {dataset_name}", flush=True)


# The --mask reruns of the comparison sweeps read one frozen TATT
# dataset descriptor per scale-cut mask: identical to the base TATT
# descriptor except for its mask_file line (the entries of
# cocoa_test_utils.FASTPT_MASK_DATASETS). variant -> (base, mask).
TATT_MASK_VARIANTS = {
    "tatt_roman_real_ones.dataset": ("tatt_roman_real.dataset", "ones.mask"),
}

def generate_tatt_mask_datasets():
    """Write the per-mask TATT dataset descriptors.

    Each variant is the base TATT descriptor with only its mask_file
    line retyped: the comparison sweeps read them through the --mask
    option to evaluate the same generated vector under another
    scale-cut mask. Pure text, no model evaluations, so the variants
    regenerate in the --overwrite run and in the incremental
    --tatt-masks mode alike.

    Returns:
      nothing; frozen/data/ gains one descriptor per variant.

    Raises:
      RuntimeError when a base descriptor does not contain exactly
      one mask_file line.
    """
    data_dir = os.path.join(u.FROZEN_DIR, "data")
    for variant, (base, mask) in TATT_MASK_VARIANTS.items():
        with open(os.path.join(data_dir, base)) as f:
            descriptor = f.read()
        replaced = 0
        out_lines = []
        # keepends=True keeps the newline on every line, so joining
        # the pieces rebuilds the file byte for byte and only the
        # retyped line differs
        for line in descriptor.splitlines(keepends=True):
            if line.strip().startswith("mask_file"):
                out_lines.append(f"mask_file = {mask}\n")
                replaced += 1
            else:
                out_lines.append(line)
        if replaced != 1:
            raise RuntimeError(
                f"{base}: expected exactly one mask_file line, "
                f"found {replaced}")
        with open(os.path.join(data_dir, variant), "w") as f:
            f.write("".join(out_lines))
        print(f"TATT mask variant: {variant} (mask_file = {mask})",
              flush=True)


def generate_halo_reference(stamp):
    """Write frozen/halo_reference.json, the ground truth of test_halo.py.

    The probe grids, the configuration and the pinned HOD and gas
    parameters all live in test_halo.py, which this function imports,
    so the generator and the tests can never describe different
    states. It builds that state (a model at the frozen fiducial
    point), evaluates every probe the current halo.c can evaluate, and
    stores inputs and values together; the probes listed in
    test_halo.HEAD_DEFECTS abort the process on the current halo.c and
    are left out (the _meta block records the list). Runs inside a
    --halo-one worker subprocess: it builds a model (see main's note).

    Arguments:
      stamp = the UTC time string written into the _meta block.

    Returns:
      nothing; frozen/halo_reference.json is written.

    Raises:
      whatever test_halo.build_halo_state raises when the model fails
      to build or evaluate.
    """
    # test_halo sits next to this script, on the path inserted at the
    # top of the file
    import test_halo as th

    t0 = time.time()
    print("freezing the halo.c probes ...", flush=True)
    state = th.build_halo_state()
    probes = th.freeze_probes(state)
    # dict(a, **b) builds one dictionary from a's entries plus b's:
    # the generation record plus the settings the values depend on
    reference = {
        "_meta": dict({"generated_utc": stamp,
                       "omp_num_threads": os.environ["OMP_NUM_THREADS"]},
                      **th.frozen_meta()),
        "probes": probes,
    }
    with open(th.HALO_REFERENCE_FILE, "w") as f:
        # written like the chi2 reference file; json stores the floats
        # in their shortest exact form, so every value round-trips
        # bit for bit
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"halo reference: {len(probes)} probes frozen "
          f"({time.time() - t0:.1f}s); left out (current halo.c "
          f"defects): {sorted(th.HEAD_DEFECTS)}", flush=True)


def main():
    # worker modes first: --freeze-one X and --tatt-one D each run a
    # single model-building step and exit. The parent below spawns one
    # subprocess per step: a process that initializes configurations
    # with different data-set dimensions aborts inside cosmolike (see
    # cocoa_test_utils), and one architecture serves every project.
    if "--freeze-one" in sys.argv:
        u.require_cocoa_environment()
        # sys.argv.index finds the flag's position in the argument
        # list; the entry after it (+ 1) is the flag's value
        example = sys.argv[sys.argv.index("--freeze-one") + 1]
        stamp = sys.argv[sys.argv.index("--stamp") + 1]
        freeze_example(example, stamp)
        return 0
    if "--baryon-one" in sys.argv:
        u.require_cocoa_environment()
        label = sys.argv[sys.argv.index("--baryon-one") + 1]
        generate_baryon_datavector(label)
        return
    if "--tatt-one" in sys.argv:
        u.require_cocoa_environment()
        dataset_name = sys.argv[sys.argv.index("--tatt-one") + 1]
        generate_tatt_datavector(dataset_name)
        return 0
    if "--halo-one" in sys.argv:
        u.require_cocoa_environment()
        stamp = sys.argv[sys.argv.index("--stamp") + 1]
        generate_halo_reference(stamp)
        return 0
    """Rebuild tests/frozen/ and the manifest from the current project.

    The steps, in order: refuse without --overwrite; delete and
    recreate frozen/; copy the data and the example snapshots; write
    the two expanded frozen-configuration modules; freeze the halo.c
    probe values of test_halo.py; evaluate the four reference chi2
    values from those modules (the same code path the tests use);
    write the reference file; hash everything into the manifest. The
    manifest comes last so it covers every file the earlier steps
    produced.

    Returns:
      0 on success, 1 when --overwrite was not given (the usage text
      and the refusal reason are printed).
    """
    if "--tatt-masks" in sys.argv:
        # incremental: rewrite the per-mask TATT descriptors of the
        # --mask comparison sweeps in an existing frozen state and
        # re-pin the manifest; pure text, no model evaluations
        u.require_cocoa_environment()
        generate_tatt_mask_datasets()
        manifest = {
            "_comment": "SHA-256 of every file under tests/frozen/; "
                        "verified by every test before evaluating "
                        "anything.",
            "files": u.compute_manifest(),
        }
        with open(u.MANIFEST_FILE, "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"manifest: {len(manifest['files'])} files pinned")
        return
    if "--baryons" in sys.argv:
        # incremental: add the per-method frozen baryon vectors of the
        # DRIFT tests to an existing frozen state and re-pin the
        # manifest; nothing else changes
        import subprocess

        u.require_cocoa_environment()
        self_path = os.path.abspath(__file__)
        for label, _, _ in u.BARYON_METHODS:
            completed = subprocess.run(
                [sys.executable, self_path, "--baryon-one", label])
            if completed.returncode != 0:
                raise RuntimeError(f"baryon worker for {label!r} failed")
        manifest = {
            "_comment": "SHA-256 of every file under tests/frozen/; "
                        "verified by every test before evaluating "
                        "anything.",
            "files": u.compute_manifest(),
        }
        with open(u.MANIFEST_FILE, "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"manifest: {len(manifest['files'])} files pinned")
        return
    if "--halo" in sys.argv:
        # incremental: (re)write frozen/halo_reference.json, the
        # halo.c ground truth of test_halo.py, in an existing frozen
        # state and re-pin the manifest; nothing else changes
        import subprocess

        u.require_cocoa_environment()
        stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        completed = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--halo-one",
             "--stamp", stamp])
        if completed.returncode != 0:
            raise RuntimeError("halo worker failed")
        manifest = {
            "_comment": "SHA-256 of every file under tests/frozen/; "
                        "verified by every test before evaluating "
                        "anything.",
            "files": u.compute_manifest(),
        }
        with open(u.MANIFEST_FILE, "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"manifest: {len(manifest['files'])} files pinned")
        return
    if "--overwrite" not in sys.argv:
        print(__doc__)
        print("Refusing to run without --overwrite (this redefines the "
              "frozen state every test compares against).")
        return 1
    u.require_cocoa_environment()
    # time.gmtime() is the current time in UTC; strftime prints it
    # in the ISO form the frozen-module headers carry
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if os.path.isdir(u.FROZEN_DIR):
        shutil.rmtree(u.FROZEN_DIR)
    os.makedirs(u.FROZEN_DIR)

    print("freezing ../data ...", flush=True)
    # the data copy is what lets users change ../data later without
    # touching the tests; .DS_Store (macOS Finder metadata) would only
    # pollute the manifest
    # ignore_patterns builds the filter function copytree consults
    # in every folder it copies; each .DS_Store match is skipped
    shutil.copytree(os.path.join(PROJECT_DIR, "data"),
                    os.path.join(u.FROZEN_DIR, "data"),
                    ignore=shutil.ignore_patterns(".DS_Store"))
    # .values() iterates the entry dictionaries; the keys are not
    # needed for the snapshot copies
    for cfg in u.EXAMPLES.values():
        shutil.copy2(os.path.join(PROJECT_DIR, cfg["provenance"]),
                     os.path.join(u.FROZEN_DIR, cfg["provenance"]))

    # one worker subprocess per model-building step (see main's note)
    import subprocess
    # __file__ is this script's own path: each worker re-runs this
    # same file with a worker flag
    self_path = os.path.abspath(__file__)
    # iterating a dictionary yields its keys: the configuration names
    for example in u.EXAMPLES:
        completed = subprocess.run(
            [sys.executable, self_path, "--freeze-one", example,
             "--stamp", stamp])
        if completed.returncode != 0:
            raise RuntimeError(f"freeze worker for {example} failed")
    # the TATT-generated data vectors must exist before the reference
    # loop below: every TATT reference evaluates against them
    for dataset_name in u.TATT_GENERATORS:
        completed = subprocess.run(
            [sys.executable, self_path, "--tatt-one", dataset_name])
        if completed.returncode != 0:
            raise RuntimeError(f"TATT worker for {dataset_name} failed")

    generate_tatt_mask_datasets()

    # the halo.c ground truth of test_halo.py; its model uses the TATT
    # dataset, so it runs after the TATT worker above
    completed = subprocess.run(
        [sys.executable, self_path, "--halo-one", "--stamp", stamp])
    if completed.returncode != 0:
        raise RuntimeError("halo worker failed")

    reference = {
        "_meta": {
            "generated_utc": stamp,
            "omp_num_threads": os.environ["OMP_NUM_THREADS"],
            "chi2_tolerance": u.CHI2_TOLERANCE,
        }
    }
    for example in u.EXAMPLES:
        for tatt in (False, True):
            # the a-if-else inside the braces picks the variant
            # suffix for the reference key
            key = f"{example}_{'tatt' if tatt else 'nla'}"
            t0 = time.time()
            chi2 = u.single_model_chi2(example, tatt)
            # :.6f = fixed six decimals; :.1f prints the elapsed
            # seconds with one decimal
            print(f"{key}: chi2 = {chi2:.6f}  ({time.time() - t0:.1f}s)",
                  flush=True)
            reference[key] = chi2

    with open(u.REFERENCE_FILE, "w") as f:
        # indent=2 pretty-prints; sort_keys fixes the key order so
        # the file diffs cleanly; the extra write ends the file with
        # a final newline
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")

    # compute_manifest returns {relative path: sha256} for every file
    # now under frozen/; writing it LAST means it covers every file
    # the steps above produced
    manifest = {
        "_comment": "SHA-256 of every file under tests/frozen/; verified by "
                    "every test before evaluating anything.",
        "files": u.compute_manifest(),
    }
    with open(u.MANIFEST_FILE, "w") as f:
        # written exactly like the reference file above
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"manifest: {len(manifest['files'])} files pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
